// server.js — Express backend (Vendorapay token flow + PayPal + M-Pesa placeholders)
require('dotenv').config();
const express = require('express');
const axios = require('axios');
const bodyParser = require('body-parser');
const cors = require('cors');
const dayjs = require('dayjs');

const app = express();
app.use(cors());
app.use(bodyParser.json());
app.use('/assets', express.static('assets'));

const PORT = process.env.PORT || 3000;

/* ---------------- Vendorapay charge using token (server side) ----------------
  - Frontend sends token (nonce) generated by Hosted Fields.
  - Server calls Vendorapay API (authenticated with VENDORAPAY_API_KEY) to create charge.
  - Response should be validated and stored; webhooks used for async confirmation.
---------------------------------------------------------------------------- */
const VENDORAPAY_API_BASE = process.env.VENDORAPAY_API_BASE || 'https://vendorapay.com/api';
const VENDORAPAY_API_KEY = process.env.VENDORAPAY_API_KEY; // set in .env

if (!VENDORAPAY_API_KEY) {
  console.warn('AVISO: VENDORAPAY_API_KEY não definida nas variáveis de ambiente.');
}

app.post('/api/vendorapay/charge', async (req, res) => {
  try {
    const { token, amount, currency, description } = req.body;
    if (!token || !amount) return res.status(400).json({ success: false, message: 'token e amount são obrigatórios' });

    // Build payload per Vendorapay API spec (ajuste campos se necessário)
    const payload = {
      token,             // token gerado pelo Hosted Fields
      amount,
      currency: currency || 'MZN',
      description: description || 'Compra MZ TECH STORE',
      reference: `MZTECH-${Date.now()}`
    };

    const response = await axios.post(`${VENDORAPAY_API_BASE}/payments`, payload, {
      headers: { Authorization: `Bearer ${VENDORAPAY_API_KEY}`, 'Content-Type': 'application/json' },
      timeout: 15000
    });

    // Vendorapay should return success / transaction id
    const data = response.data;
    // Save order to DB here (not implemented)

    return res.status(200).json({ success: true, transactionId: data.transactionId || data.id || null, raw: data });
  } catch (err) {
    console.error('Vendorapay charge erro:', err.response ? err.response.data : err.message);
    const msg = err.response && err.response.data && err.response.data.message ? err.response.data.message : err.message;
    return res.status(500).json({ success: false, message: 'Erro ao processar pagamento Vendorapay', details: msg });
  }
});

/* ---------------- PayPal endpoints (Orders v2) ---------------- */
const PAYPAL_CLIENT = process.env.PAYPAL_CLIENT_ID;
const PAYPAL_SECRET = process.env.PAYPAL_SECRET;
const PAYPAL_BASE = process.env.PAYPAL_ENV === 'live' ? 'https://api-m.paypal.com' : 'https://api-m.sandbox.paypal.com';

async function paypalGetAccessToken() {
  const auth = Buffer.from(`${PAYPAL_CLIENT}:${PAYPAL_SECRET}`).toString('base64');
  const r = await axios.post(`${PAYPAL_BASE}/v1/oauth2/token`, 'grant_type=client_credentials', {
    headers: { Authorization: `Basic ${auth}`, 'Content-Type': 'application/x-www-form-urlencoded' }
  });
  return r.data.access_token;
}

app.post('/api/paypal/create-order', async (req, res) => {
  try {
    const amount = (req.body && req.body.amount) ? String(req.body.amount) : '400';
    const token = await paypalGetAccessToken();
    const order = await axios.post(`${PAYPAL_BASE}/v2/checkout/orders`, {
      intent: 'CAPTURE',
      purchase_units: [{ amount: { currency_code: 'MZN', value: amount } }]
    }, { headers: { Authorization: `Bearer ${token}` }});
    res.json(order.data);
  } catch (err) {
    console.error('PayPal create-order error', err.response ? err.response.data : err.message);
    res.status(500).json({ error: 'Erro criando ordem PayPal', details: err.response ? err.response.data : err.message });
  }
});

app.post('/api/paypal/capture/:orderID', async (req, res) => {
  try {
    const token = await paypalGetAccessToken();
    const capture = await axios.post(`${PAYPAL_BASE}/v2/checkout/orders/${req.params.orderID}/capture`, {}, {
      headers: { Authorization: `Bearer ${token}` }
    });
    // Save order, deliver product, etc.
    res.json(capture.data);
  } catch (err) {
    console.error('PayPal capture error', err.response ? err.response.data : err.message);
    res.status(500).json({ error: 'Erro ao capturar ordem PayPal', details: err.response ? err.response.data : err.message });
  }
});

/* ---------------- M-Pesa STK Push (placeholder) ----------------
   Implement per your operator's API (Safaricom Daraja or local aggregator)
------------------------------------------------------------------*/
const MPESA_PROVIDER = (process.env.MPESA_PROVIDER || 'safaricom').toLowerCase();
const MPESA_CONFIG = {
  safaricom: {
    oauthUrl: process.env.MPESA_OAUTH_URL || 'https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials',
    stkPushUrl: process.env.MPESA_STK_URL || 'https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest',
    consumerKey: process.env.MPESA_CONSUMER_KEY,
    consumerSecret: process.env.MPESA_CONSUMER_SECRET,
    shortcode: process.env.MPESA_SHORTCODE,
    passkey: process.env.MPESA_PASSKEY,
    callbackUrl: process.env.MPESA_CALLBACK_URL
  }
};

app.post('/api/mpesa/stkpush', async (req, res) => {
  try {
    const { phone, amount } = req.body;
    if (!phone) return res.status(400).json({ message: 'phone required' });
    // Implement STK push using your provider's docs; here return placeholder
    // e.g., call mpesa OAuth, build password, call stkPushUrl
    return res.json({ message: 'STK Push iniciado (placeholder). Implemente integração Daraja/fornecedor.' });
  } catch (err) {
    console.error('mpesa error', err);
    res.status(500).json({ message: 'Erro M-Pesa' });
  }
});

/* ---------------- Vendorapay webhook (to receive async notifications) ----------------
   Ensure the webhook endpoint is configured on Vendorapay dashboard to point here.
-------------------------------------------------------------------------------------*/
app.post('/api/vendorapay/webhook', async (req, res) => {
  // Validate webhook signature per Vendorapay docs (if provided)
  console.log('Vendorapay webhook received:', req.headers, req.body);
  // Update order status in DB accordingly
  res.status(200).send('OK');
});

/* ---------------- start server ---------------- */
app.get('/api/health', (req, res) => res.json({ ok: true }));
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
